id: conference-2012-power-distribution-network-reconfiguration
category: conference
title: Power Distribution Network Reconfiguration for Bounded Transient Power Loss
authors:
  - name: Z. Li et al.
venue: ISGT Asia
year: 2012
dateDisplay: May 2012
