id: conference-2020-freac-cache-folded-logic-reconfigurable
category: conference
title: "FReaC Cache: Folded Logic Reconfigurable Computing in the Last Level Cache"
authors:
  - name: A. Dhar et al.
venue: MICRO-53
year: 2020
dateDisplay: October 2020
