id: conference-2016-novel-applications
category: conference
title: Novel Applications of Deep Learning Hidden Features for Adaptive Testing
authors:
  - name: B. Xiao et al.
venue: ASP-DAC
year: 2016
dateDisplay: January 2016
