id: conference-2021-graviton-a-reconfigurable-memory-compute-fabric
category: conference
title: "Graviton: A Reconfigurable Memory-Compute Fabric for Data Intensive Applications"
authors:
  - name: A. Dhar et al.
venue: ARC
year: 2021
dateDisplay: June 2021
