id: conference-2018-application-transparent-near-memory-processing-architecture
category: conference
title: Application-Transparent Near-Memory Processing Architecture with Memory Channel Network
authors:
  - name: M. Alian et al.
venue: MICRO'51
year: 2018
dateDisplay: October 2018
