// Derive form fields directly from the Zod schemas in lib/content/schema.ts.
//
// This is the single most important design decision in Studio. Forms are NOT hand-written
// per entity — they are generated by walking the same schema that CI validates against.
// Two consequences that matter for a system meant to outlive its author's attention:
//
//   1. A form can never accept something the build would reject, or omit a field the build
//      requires. Drift between "what the UI allows" and "what is valid" is impossible.
//   2. Adding a field to the content model makes it appear in Studio automatically. The
//      one-line schema edit IS the feature.
//
// Presentation-only hints (nicer labels, textarea vs input, ordering) live in OVERRIDES
// below. They are optional decoration; a field with no override still renders correctly.
"use client";

import type { ZodType } from "zod";

export type FieldKind =
  | "string"
  | "text"
  | "number"
  | "boolean"
  | "enum"
  | "array"
  | "object"
  | "unknown";

export interface FieldSpec {
  key: string;
  label: string;
  kind: FieldKind;
  optional: boolean;
  nullable: boolean;
  defaultValue?: unknown;
  /** Enum members, when kind === "enum". */
  options?: string[];
  /** Item shape, when kind === "array". */
  element?: FieldSpec;
  /** Child fields, when kind === "object". */
  fields?: FieldSpec[];
  help?: string;
  /** Rendered but never editable (identifiers, machine-managed provenance). */
  readOnly?: boolean;
  /** An image path — the UI offers a picker/upload rather than a text box. */
  asset?: boolean;
}

// Zod does not publish types for its internal `def` structure, so walking a schema means
// reaching past the public surface. Contained to this one declaration and accessor, and
// described precisely enough that the rest of the file stays type-checked.
interface ZodDef {
  type?: string;
  shape?: Record<string, unknown>;
  innerType?: unknown;
  defaultValue?: unknown;
  element?: unknown;
  entries?: Record<string, unknown>;
  values?: unknown[];
  options?: unknown[];
  getter?: () => unknown;
  in?: unknown;
  out?: unknown;
}

const def = (schema: unknown): ZodDef =>
  (schema as { _zod?: { def?: ZodDef } })?._zod?.def ??
  (schema as { def?: ZodDef })?.def ??
  {};

/** Title-case a camelCase key: `roleTitle` -> `Role title`. */
function humanize(key: string): string {
  const spaced = key
    .replace(/^_/, "")
    .replace(/([A-Z])/g, " $1")
    .replace(/\bUrl\b/i, "URL")
    .replace(/\bId\b/, "ID")
    .trim();
  return spaced.charAt(0).toUpperCase() + spaced.slice(1).toLowerCase().replace(/\burl\b/, "URL").replace(/\bid\b/, "ID");
}

/** Presentation hints. Purely optional — omit a field and it still renders. */
const OVERRIDES: Record<string, Partial<FieldSpec>> = {
  id: { readOnly: true, help: "Permanent identifier. Also the filename — it cannot be changed after creation." },
  _meta: { readOnly: true, label: "Provenance", help: "Where this record came from. Machine-managed." },
  updatedAt: { readOnly: true },
  updatedBy: { readOnly: true },
  bio: { kind: "text" },
  description: { kind: "text" },
  longDescription: { kind: "text" },
  shortDescription: { kind: "text" },
  summary: { kind: "text" },
  body: { kind: "text", help: "Markdown. Renders as the post body." },
  researchPhilosophy: { kind: "text" },
  futureVision: { kind: "text" },
  quote: { kind: "text" },
  recruitingNotice: { kind: "text" },
  note: { kind: "text" },
  photo: { asset: true },
  thumbnail: { asset: true },
  logo: { asset: true },
  image: { asset: true },
  themeIds: { help: "Research thrusts this belongs to. Untagged records do not appear in the research browser." },
  status: { help: "Only 'published' records appear on the public site." },
  featured: { help: "Featured items are highlighted on the homepage." },
};

/** Field display order. Anything unlisted keeps schema order, after these. */
const ORDER = [
  "id",
  "status",
  "name",
  "title",
  "kind",
  "category",
  "personType",
  "roleTitle",
  "tagline",
  "summary",
  "date",
  "year",
];

/**
 * Peel wrapper types (optional / default / nullable / preprocess pipes / lazy) down to the
 * schema that actually describes the value, remembering what the wrappers told us.
 */
function unwrap(schema: unknown): {
  inner: any;
  optional: boolean;
  nullable: boolean;
  defaultValue?: unknown;
} {
  let cur: any = schema;
  let optional = false;
  let nullable = false;
  let defaultValue: unknown;

  // Bounded rather than while(true): a malformed or cyclic schema must not hang the browser.
  for (let i = 0; i < 12; i++) {
    const d = def(cur);
    if (d.type === "optional") {
      optional = true;
      cur = d.innerType;
    } else if (d.type === "nullable") {
      nullable = true;
      cur = d.innerType;
    } else if (d.type === "default" || d.type === "prefault") {
      defaultValue = typeof d.defaultValue === "function" ? d.defaultValue() : d.defaultValue;
      cur = d.innerType;
    } else if (d.type === "pipe") {
      // z.preprocess(...) — the output side is the real shape.
      cur = d.out ?? d.in;
    } else if (d.type === "lazy") {
      cur = typeof d.getter === "function" ? d.getter() : cur;
      break;
    } else {
      break;
    }
  }
  return { inner: cur, optional, nullable, defaultValue };
}

function describe(key: string, schema: unknown): FieldSpec {
  const { inner, optional, nullable, defaultValue } = unwrap(schema);
  const d = def(inner);

  let kind: FieldKind = "unknown";
  let options: string[] | undefined;
  let element: FieldSpec | undefined;
  let fields: FieldSpec[] | undefined;

  switch (d.type) {
    case "string":
      kind = "string";
      break;
    case "number":
    case "int":
      kind = "number";
      break;
    case "boolean":
      kind = "boolean";
      break;
    case "enum":
      kind = "enum";
      options = Object.keys(d.entries ?? {});
      break;
    case "literal":
      kind = "enum";
      options = (d.values ?? []).map(String);
      break;
    case "array":
      kind = "array";
      element = describe("item", d.element);
      break;
    case "object":
      kind = "object";
      fields = fieldsOf(inner);
      break;
    default:
      kind = "unknown";
  }

  const base: FieldSpec = {
    key,
    label: humanize(key),
    kind,
    optional,
    nullable,
    defaultValue,
    options,
    element,
    fields,
  };
  return { ...base, ...OVERRIDES[key] };
}

/** Field list for a Zod object schema, in display order. */
export function fieldsOf(schema: unknown): FieldSpec[] {
  const shape = def(schema).shape;
  if (!shape) return [];
  const specs = Object.entries(shape).map(([key, sub]) => describe(key, sub));
  return specs.sort((a, b) => {
    const ai = ORDER.indexOf(a.key);
    const bi = ORDER.indexOf(b.key);
    if (ai !== -1 || bi !== -1) return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
    return 0;
  });
}

/**
 * Publication is a discriminated union on `category`, so its fields depend on which kind of
 * publication is being edited. Returns the member schema for a given discriminator value.
 */
export function unionMember(schema: unknown, discriminator: string, value: string): unknown {
  const options = def(schema).options ?? [];
  for (const opt of options) {
    const litDef = def(def(opt).shape?.[discriminator]);
    const values: unknown[] = litDef.values ?? Object.keys(litDef.entries ?? {});
    if (values.map(String).includes(value)) return opt;
  }
  return options[0];
}

export function unionValues(schema: unknown, discriminator: string): string[] {
  return (def(schema).options ?? []).flatMap((opt: unknown) => {
    const litDef = def(def(opt).shape?.[discriminator]);
    return (litDef.values ?? Object.keys(litDef.entries ?? {})).map(String);
  });
}

/** Validate a candidate record, returning per-field messages keyed by dotted path. */
export function validateRecord(
  schema: ZodType,
  value: unknown
): { ok: true } | { ok: false; errors: Record<string, string> } {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true };
  const errors: Record<string, string> = {};
  for (const issue of result.error.issues) {
    errors[issue.path.join(".") || "_"] = issue.message;
  }
  return { ok: false, errors };
}
